### ISSUE TITLE
have a way to run other commands

### ISSUE THREAD

**Issue by nvdk** [erikap/docker-ruby-sinatra#2]
Currently the only option is to start sinatra, but it could be nice to run any command available in the bundle (eg bundle exec rspec for tests, rake tasks, ...).

May produce a pull request if I find the time :)

**Comment by erikap** [comment]
Added a new feature in 2e1ca8afc6a5ae87374b5b9845e7a7b15b2b8f1c: when the container starts with `RACK_ENV=test` the `rspec` command is executed by default.

You can use Docker's `--entrypoint` option to overwrite the default command that is executed on container startup. More info can be found in the [Docker documentation](https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime). 
E.g.
```
docker run --name my-sinatra-app \
      -v /path/to/sinatra/app:/usr/src/app \
     --entrypoint bundle
      erikap/ruby-sinatra exec rspec
```

**Comment by erikap** [comment]
@nvdk: I will close the issue. Feel free to re-open if you're not satisfied with the solution.

**Comment by nvdk** [comment]
Your solution suits my needs :+1: . I didn't know you could overwrite the entrypoint from the command line, learned something new :)
